spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/api/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service-cb
                fallbackUri: "forward:/fallback/user-service"
        - id: listing-service
          uri: lb://listingservice
          predicates:
            - Path=/api/listings/**
          filters:
            - name: CircuitBreaker
              args:
                name: listing-service-cb
                fallbackUri: "forward:/fallback/listing-service"
        - id: messaging-service
          uri: lb://messagingservice
          predicates:
            - Path=/api/messages/**
          filters:
            - name: CircuitBreaker
              args:
                name: messaging-service-cb
                fallbackUri: "forward:/fallback/messaging-service"
        - id: notification-service
          uri: lb://notificationservice
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notification-service-cb
                fallbackUri: "forward:/fallback/notification-service"

resilience4j:
  circuitbreaker:
    instances:
      user-service-cb:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

      listing-service-cb:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

      messaging-service-cb:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

      notification-service-cb:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://eureka-server:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read_only
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

jwt:
  secret-key: PfbQBaBhujiLiq1htDnUaCO60rvxBLDzCclt/cLGh8g=
  expiration: 86400000

info:
  app:
    name: "gatewayserver"
    description: "Edge Server for Local Market Project"
    version: ${app.version:1.0.0}
