spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/user/**
        - id: listingservice
          uri: lb://LISTINGSERVICE
          predicates:
            - Path=/api/listings/** 
        - id: messagingservice
          uri: lb://MESSAGINGSERVICE
          predicates:
            - Path=/api/messages/**
        - id: notificationservice
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/api/notifications/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read_only
  info:
    env:
      enabled: true

jwt:
  secret-key: PfbQBaBhujiLiq1htDnUaCO60rvxBLDzCclt/cLGh8g=
  expiration: 86400000

info:
  app:
    name: "gatewayserver"
    description: "Edge Server for Local Market Project"
    version: ${app.version:1.0.0}
