spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: listing-service
          uri: lb://listing-service
          predicates:
            - Path=/api/listings/** 
        - id: messaging-service
          uri: lb://messaging-service
          predicates:
            - Path=/api/messages/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://eureka-server/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read_only
  info:
    env:
      enabled: true

jwt:
  secret-key: PfbQBaBhujiLiq1htDnUaCO60rvxBLDzCclt/cLGh8g=
  expiration: 86400000

info:
  app:
    name: "gatewayserver"
    description: "Edge Server for Local Market Project"
    version: ${app.version:1.0.0}
