spring:
  application:
    name: listingservice

  datasource:
    url: jdbc:mysql://localhost:3308/listingdb
    username: marketplace-test
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

server:
  port: 8083
  shutdown: graceful

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

r2:
  accessKeyId: 3181ba84d2ec95fa1d5678c23c5dc075
  secretAccessKey: 8216132a70425a8c584c53e5c68bcccc89145ab1d62996a0917c658b1608fd8c
  endpoint: https://f268dbfa80276e12efddf04a916173c5.r2.cloudflarestorage.com/local-market-listings
  bucketName: local-market-listings

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: none
    health:
      probes:
        enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "listing_service"
    description: "Listing TEST Service for Local Market Project"
    version: "0.0.1"