spring:
  application:
    name: messagingservice

  datasource:
    url: jdbc:mysql://mysql-messaging:3306/messagingdb
    username: marketplace-test
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

messaging:
  exchange: message-exchange
  routing-key: message.notification 

jwt:
  secret-key: PfbQBaBhujiLiq1htDnUaCO60rvxBLDzCclt/cLGh8g=
  expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

info:
  app:
    name: "messagingservice"
    description: "Messaging Service for Local Market Project"
    version: 1.0.0
