spring:
  application:
    name: notificationservice

  datasource:
    url: jdbc:mysql://localhost:3308/marketplace_notifications?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: marketplace-test
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

notification:
  queue: notification-queue

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "notificationservice"
    description: "Notification Service for Local Market Project"
    version: 1.0.0
