spring:
  application:
    name: userservice

  datasource:
    url: jdbc:mysql://mysql-user:3306/userdb
    username: marketplace-test
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

jwt:
  secret-key: PfbQBaBhujiLiq1htDnUaCO60rvxBLDzCclt/cLGh8g=
  expiration: 86400000

r2:
  accessKeyId: 3181ba84d2ec95fa1d5678c23c5dc075
  secretAccessKey: 8216132a70425a8c584c53e5c68bcccc89145ab1d62996a0917c658b1608fd8c
  endpoint: https://f268dbfa80276e12efddf04a916173c5.r2.cloudflarestorage.com/local-market-users
  bucketName: local-market-users

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    com:
      localmarket:
        user_service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  app:
    name: "userservice"
    description: "User Service for Local Market Project"
    version: "1.0.0"
